<?

$_URL = 'http://www.imdb.com/title/tt0118715/quotes';
$_ADVERTS = array(
	array('Walter','You see what happens, Larry?',$_URL),
	array('Walter','I don\'t roll on Shabbos!',$_URL),
    array('Blond Thug','Where\'s the money, Lebowski?',$_URL),
    array('Nihilist','We believe in nothing, Lebowski.',$_URL),
    array('Walter','Is this your homework, Larry?',$_URL),
    array('Nihilist','Ve vant ze money, Lebowski',$_URL),
);

$_SECTIONS = array(
    array(1234,'The Dude',0),
    array(2345,'Walter Sobchak',0),
    array(3456,'Donny',1),
    array(4567,'Maude Lebowski',0),
    array(5678,'The Big Lebowski',0),
    array(6789,'Brandt',0),
    array(7890,'Jesus Quintana',0),
);


$_STAT = array(
	'TOTAL' 	=> 654329,
	'ONLINE' 	=> array(
		array(0,'true'), 
		array(1,'false'),
        array(2,'short'), 
		array(3,'long'), 
		array(4,'apha'), 
		array(5,'omega'),
		array(6,'drag'),
		array(7,'drop'),
		array(8,'make'),
		array(9,'clean'),
		array(10,'east'),
		array(11,'west'), 
		array(12,'up'),
		array(13,'down'), 
		array(14,'sun'), 
		array(15,'rain'),
		array(16,'secondary'),
		array(17,'main')
	)
);



$_POLL = array(
	'TITLE'		=> 'Something plain',
	'QUESTION'	=> 'Mr. Treehorn draws a lot of water in this town. You don\'t draw shit, Lebowski. Now we got a nice, quiet little beach community here, and I aim to keep it nice and quiet. So let me make something plain. I don\'t like you sucking around, bothering our citizens, Lebowski. I don\'t like your jerk-off name. I don\'t like your jerk-off face. I don\'t like your jerk-off behavior, and I don\'t like you, jerk-off. Do I make myself clear?',
	'ANSWERS'	=> array(
		0 => 'Yes, sir',
		1 => 'Definitely, sir',
		2 => 'Sorry, i wasn\'t listening'
	),
	'BUTTON' => 'OK'
);


$_NEWS = array(
	array('03:45',987,'The Stranger','See, they call Los Angeles the "City Of Angels"; but I didn\'t find it to be that, exactly. But I\'ll allow it as there are s ome nice folks there. \'Course I ain\'t never been to London, and I ain\'t never seen France. And I ain\'t never seen no queen in her damned undies, so the feller says. But I\'ll tell you what - after seeing Los Angeles, and this here story I\'m about to unfold, well, I guess I seen somethin\' every bit as stupefyin\' as you\'d seen in any of them other places. And in English , too. So I can die with a smile on my face, without feelin\' like the good Lord gypped me. Now this here story I\'m about to unfold took place in the early \'90s - just about the time of our conflict with Sad\'m and the I-raqis. I only mention it be cause sometimes there\'s a man...'),
	array('03:48',876,'The Stranger','...I won\'t say a hero, \'cause, what\'s a hero? Sometimes, there\'s a man. And I\'m talkin\' about the Dude here - the Dude from Los Angeles. Sometimes, there\'s a man, well, he\'s the man for his time and place. He fits right in there. And that\'s the Dude. The Dude, from Los Angeles. And even if he\'s a lazy man - and the Dude was most certainly that. Quite possibly the laziest in all of Los Angeles County, which would place him high in the runnin\' for laziest worldwide. Sometimes there\'s a man , sometimes, there\'s a man. Well, I lost my train of thought here. But... aw, hell. I\'ve done introduced it enough.'),
	array('03:50',765,'Walter Sobchak','Donny was a good bowler, and a good man. He was one of us. He was a man who loved the outdoors... and bowling, and as a surfer he explored the beaches of Southern California, from La Jolla to Leo Carrillo and... up to... Pismo. He died, like so many young men of his generation, he died before his time. In your wisdom, Lord, you took him, as you took so many bright flowering young men at Khe Sanh, at Langdok, at Hill 364. These young men gave their lives. And so would Donny. Donny, who loved bowling. And so, Theodore Donald Karabotsos, in accordance with what we think your dying wishes might well have been, we commit your final mortal remains to the bosom of the Pacific Ocean, which you loved so well. Good night, sweet prince.'),
	array('03:52',654,'The Dude','God damn you Walter! You fuckin\' asshole! Everything\'s a fuckin\' travesty with you, man! And what was all that shit about Vietnam? What the FUCK, has anything got to do with Vietnam? What the fuck are you talking about?'),
	array('03:57',543,'Jesus Quintana','What\'s this day of rest shit? What\'s this bullshit? I don\'t fuckin\' care! It don\'t matter to Jesus. But you\'re not foolin\'me, man. You might fool the fucks in the league office, but you don\'t fool Jesus. This bush league psyche-out stuff. Laughable, man - ha ha! I would have fucked you in the ass Saturday. I fuck you in the ass next Wednesday instead. Wooo! You gotadate Wednesday, baby!'),
	array('03:59',432,'Jesus Quintana','Let me tell you something, pendejo. You pull any of your crazy shit with us, you flash a piece out on the lanes, I\'ll take it away from you, stick it up your ass and pull the fucking trigger \'til it goes "click."'),
	array('04:01',321,'The Dude','Let me explain something to you. Um, I am not "Mr. Lebowski". You\'re Mr. Lebowski. I\'m the Dude. So that\'s what you call me. You know, that or, uh, His Dudeness, or uh, Duder, or El Duderino if you\'re not into the whole brevity thing.')
);

$_DATA = array (
	'ADVERTS' 		=> $_ADVERTS,
    'SECTIONS' 	=> $_SECTIONS,
	'NEWS' 		=> $_NEWS,
	'POLL'		=> $_POLL,
	'STAT'		=> $_STAT
);

?>
